import type { TabId, ChecklistData, AircraftRecap, ChecklistSection } from './types';

export const TABS: TabId[] = ['LIENS', 'NOTICE', 'FAVORI', 'RECAP', 'BUBK', 'GIYA', 'GKQA', 'GLVX', 'HMPI', 'HNNY', 'HPPL'];

export const AIRCRAFT_COLORS: Partial<Record<string, { bg: string; text: string; ring: string; border: string; highlight?: string; checkbox?: string; tableHighlight?: string; }>> = {
  LIENS: { bg: 'bg-purple-600', text: 'text-white', ring: 'ring-purple-500', border: 'border-purple-500' },
  NOTICE: { bg: 'bg-purple-600', text: 'text-white', ring: 'ring-purple-500', border: 'border-purple-500' },
  FAVORI: { bg: 'bg-white', text: 'text-black', ring: 'ring-gray-400', border: 'border-yellow-500' },
  RECAP: { bg: 'bg-black', text: 'text-white', ring: 'ring-gray-400', border: 'border-gray-400' },
  BUBK: { bg: 'bg-orange-500', text: 'text-white', ring: 'ring-orange-400', border: 'border-orange-500', highlight: 'bg-orange-900/50 ring-2 ring-orange-500', checkbox: 'accent-orange-500 focus:ring-orange-500', tableHighlight: 'bg-orange-500/40' },
  GIYA: { bg: 'bg-green-500', text: 'text-white', ring: 'ring-green-400', border: 'border-green-500', highlight: 'bg-green-900/50 ring-2 ring-green-500', checkbox: 'accent-green-500 focus:ring-green-500', tableHighlight: 'bg-green-500/40' },
  GKQA: { bg: 'bg-red-300', text: 'text-red-800', ring: 'ring-red-200', border: 'border-red-300', highlight: 'bg-red-200/50 ring-2 ring-red-300', checkbox: 'accent-red-400 focus:ring-red-400', tableHighlight: 'bg-red-600/40' },
  GLVX: { bg: 'bg-blue-800', text: 'text-white', ring: 'ring-blue-600', border: 'border-blue-600', highlight: 'bg-blue-900/50 ring-2 ring-blue-700', checkbox: 'accent-blue-500 focus:ring-blue-500', tableHighlight: 'bg-blue-700/40' },
  HMPI: { bg: 'bg-sky-400', text: 'text-white', ring: 'ring-sky-300', border: 'border-sky-300', highlight: 'bg-sky-900/50 ring-2 ring-sky-400', checkbox: 'accent-sky-400 focus:ring-sky-400', tableHighlight: 'bg-sky-500/40' },
  HNNY: { bg: 'bg-amber-500', text: 'text-white', ring: 'ring-amber-400', border: 'border-amber-500', highlight: 'bg-amber-900/50 ring-2 ring-amber-500', checkbox: 'accent-amber-500 focus:ring-amber-500', tableHighlight: 'bg-amber-500/40' },
  HPPL: { bg: 'bg-yellow-400', text: 'text-gray-900', ring: 'ring-yellow-300', border: 'border-yellow-300', highlight: 'bg-yellow-900/50 ring-2 ring-yellow-400', checkbox: 'accent-yellow-400 focus:ring-yellow-400', tableHighlight: 'bg-yellow-500/40' },
  'BRIEFING PAX': { bg: 'bg-teal-500', text: 'text-white', ring: 'ring-teal-400', border: 'border-teal-500', tableHighlight: 'bg-teal-500/40' },
};

export const RECAP_DATA: AircraftRecap[] = [
    {
        id: 'BUBK', shortName: 'BK',
        cocoMax: { princ: '98 L' },
        inutilisable: { princ: '13 L' },
        conso: { perHour: '22 L/h', perMin: '0,37 L/min' },
        autonomie: { coco1: '3 h 50' },
        ventTravers: { decollage: '20 kt', atterrissage: '15 kt' },
        distances: { decollage: '422 m', atterrissage: '328 m' },
        puissance: { decollage: '2300 rpm' },
    },
    {
        id: 'GIYA', shortName: 'YA',
        cocoMax: { princ: '142 L' },
        inutilisable: { princ: '6 L' },
        conso: { perHour: '24 L/h', perMin: '0,4 L/min' },
        autonomie: { coco1: '4 h' },
        ventTravers: { decollage: '12 kt', atterrissage: '12 kt' },
        distances: { decollage: '408 m', atterrissage: '366 m' },
        puissance: { decollage: '2150 rpm' },
    },
    {
        id: 'GKQA', shortName: 'QA',
        cocoMax: { princ: '110 L' },
        inutilisable: { princ: '10 L' },
        conso: { perHour: '30 L/h', perMin: '0,50 L/min' },
        autonomie: { coco1: '3 h 20' },
        ventTravers: { decollage: '22 kt', atterrissage: '22 kt' },
        distances: { decollage: '485 m', atterrissage: '470 m' },
        puissance: { decollage: '2300 rpm' },
    },
    {
        id: 'GLVX', shortName: 'VX',
        cocoMax: { princ: '110 L', second: '50 L' },
        inutilisable: { princ: '10 L', second: '10 L' },
        conso: { perHour: '30 L/h', perMin: '0,50 L/min' },
        autonomie: { coco1: '3 h 20', coco2: '5 h' },
        ventTravers: { decollage: '22 kt', atterrissage: '22 kt' },
        distances: { decollage: '485 m', atterrissage: '470 m' },
        puissance: { decollage: '2300 rpm' },
    },
     {
        id: 'HMPI', shortName: 'PI',
        cocoMax: { princ: '120 L' },
        inutilisable: { princ: '2 L' },
        conso: { perHour: '20 L/h', perMin: '0,33 L/min' },
        autonomie: { coco1: '5 h 54' },
        ventTravers: { decollage: '18 kt', atterrissage: '18 kt' },
        distances: { decollage: '365 m', atterrissage: '428 m' },
        puissance: { decollage: '5000 rpm' },
    },
    {
        id: 'HNNY', shortName: 'NY',
        cocoMax: { princ: '120 L' },
        inutilisable: { princ: '2 L' },
        conso: { perHour: '20 L/h', perMin: '0,33 L/min' },
        autonomie: { coco1: '5 h 54' },
        ventTravers: { decollage: '18 kt', atterrissage: '18 kt' },
        distances: { decollage: '365 m', atterrissage: '428 m' },
        puissance: { decollage: '5000 rpm' },
    },
    {
        id: 'HPPL', shortName: 'PL',
        cocoMax: { princ: '120 L' },
        inutilisable: { princ: '2 L' },
        conso: { perHour: '20 L/h', perMin: '0,33 L/min' },
        autonomie: { coco1: '5 h 54' },
        ventTravers: { decollage: '18 kt', atterrissage: '18 kt' },
        distances: { decollage: '365 m', atterrissage: '428 m' },
        puissance: { decollage: '5000 rpm' },
    },
];

const bubkChecklistContent: ChecklistSection[] = [
    { title: 'PARAMETRES', items: [
        { item: 'Rotation = 65 mi/h ou 57 kt' },
        { item: 'Montée = 80 mi/h ou 70 kt' },
        { item: 'Finale = 70 mi/h ou 60 kt' },
        { item: 'Finesse max = 70 mi/h ou 60 kt' },
    ]},
    { title: 'AVANT VOL', items: [
        { item: 'Inscription planche club' },
        { item: 'Documents Avion/Pilote à bord' },
        { item: 'Météo & Notams vérifiés' },
        { item: 'Masse et centrage effectué' },
    ]},
    { title: 'PRE-VOL EXTERIEURE', items: [
        { item: 'Purges effectuées' },
        { item: 'Essence' },
        { item: 'Feux vérifiés' },
        { item: 'Alarme décrochage testée' },
        { item: 'Cache Pitot enlevé' },
        { item: 'Barre de guidage enlevée' },
        { item: 'Niveau d\'huile vérifié' },
        { item: 'Nettoyer surfaces vitrées' },
    ]},
    { title: 'PRE-VOL INTERIEURE', items: [
        { item: 'Clés retirées / dans cockpit' },
        { item: 'Ceintures attachées' },
        { item: 'Casques branchés' },
        { item: 'Commandes : libres ET dans le bon sens' },
        { item: 'Masse et centrage vérifié' },
        { item: 'Distances décollage / atterrissages vérifiées' },
        { item: 'Breakers en place' },
        { item: 'Briefing Passager' },
    ]},
    { title: 'MISE EN ROUTE', items: [
        { item: 'Portes fermées (bien vérifier)' },
        { item: 'Freins serrés (pieds sur les freins)' },
        { item: 'Essence sur ouvert' },
        { item: 'Mixture plein riche - poussée' },
        { item: 'Horamètre noté' },
        { item: 'Radio + RadioNav sur OFF' },
        { item: 'Batterie sur ON' },
        { item: 'Volets rentrés' },
        { item: 'Moteur froid → réchauffe carbu' },
        { item: 'Clés en place, sur BOTH' },
        { item: 'Injections 1 à 4 selon température (8 en hiver)' },
        { item: 'Gaz 1cm maxi' },
        { item: 'Beacon sur ON' },
        { item: 'Feux NAV si vol de nuit' },
        { item: 'Sécurité → abords dégagés' },
        { item: 'Démarreur (max 10 secondes)' },
        { item: 'Régime 1200 trs/min' },
        { item: 'Pression huile vérifiée (plage jaune/verte dans les 30 sec)' },
    ]},
    { title: 'APRES MISE EN ROUTE', items: [
        { item: 'Top chrono noté' },
        { item: 'Réchauffe carbu repoussée (froid)' },
        { item: 'Régime 1200 trs/min' },
        { item: 'Alternateur sur ON' },
        { item: 'Bille maquette sur ON' },
        { item: 'Gyros, dépression OK' },
        { item: 'Radio + RadioNav sur ON' },
        { item: 'Fréquences et volumes vérifiés' },
        { item: 'Transpondeur sur ALT + 7000' },
        { item: 'Altimètre réglé au QNH' },
        { item: 'Conservateur de Cap réglé' },
        { item: 'Compensateur vérifié (position décollage)' },
        { item: 'ATIS noté' },
        { item: 'Briefing roulage effectué' },
        { item: 'Phare sur ON' },
        { item: 'Contact radio BONJOUR' },
        { item: 'Top chrono' },
    ]},
    { title: 'ROULAGE', items: [
        { item: 'Freins : essayés' },
        { item: 'Horizon artificiel stable' },
        { item: 'Conservateur de cap + Compas vérifiés' },
        { item: 'Bille maquette dans le bon sens' },
    ]},
    { title: 'AU POINT D\'ATTENTE', items: [
        { item: 'Freins serrés (pieds sur les freins)' },
        { item: 'Régime 1200 trs/min' },
        { item: 'Phare sur OFF' },
        { item: 'T° huile suffisante' },
        { item: 'Réchauffe carbu poussée (froid)' },
        { item: 'Régime 1700 tr/min' },
        { item: 'Tests magnétos (perte 150 max | 75 entre les 2)' },
        { item: 'Réchauffe carbu testée (<200 trs/min)' },
        { item: 'Ralenti (moteur ne cale pas)' },
        { item: 'Régime 1200 trs/min' },
    ]},
    { title: 'AVANT ALIGNEMENT', items: [
        { item: 'Batterie sur ON' },
        { item: 'Alternateur sur ON' },
        { item: 'Contact magnéto sur BOTH' },
        { item: 'Réchauffe Carbu poussée (froid)' },
        { item: 'Mixture plein riche (poussée)' },
        { item: 'Essence = robinet ouvert' },
        { item: 'Huile = Pression / T° plages vertes' },
        { item: 'Volets essayés + position décollage' },
        { item: 'Horizon artificiel réglé' },
        { item: 'Bille maquette OK' },
        { item: 'Conservateur de cap réglé' },
        { item: 'Variomètre OK' },
        { item: 'Portes fermées (bien vérifier)' },
        { item: 'Ceintures attachés' },
        { item: 'Altimètre au QNH' },
        { item: 'Commandes libre ET dans le bon sens' },
        { item: 'Briefing PANNES AU DECOLLAGE' },
        { item: 'Briefing départ' },
        { item: 'Phare sur ON' },
        { item: 'Contact radio PRET au POINT d\'ATTENTE' },
    ]},
    { title: 'ALIGNEMENT / DECOLLAGE', items: [
        { item: 'Conservateur de cap réglé' },
        { item: 'Pleine puissance (mini 2300 trs/min)' },
        { item: 'TOP CHRONO Noté' },
        { item: 'Rotation = 65 mi/h ou 57 kt' },
        { item: 'Montée = 80 mi/h ou 70 kt | bille centrée' },
        { item: '500 ft/sol = phare OFF' },
    ]},
    { title: 'APRES ATTERRISSAGE', items: [
        { item: 'Piste dégagée' },
        { item: 'Régime 1200 trs/min' },
        { item: 'Réchauffe carbu poussée (froid)' },
        { item: 'Compensateur au neutre' },
        { item: 'Volets rentrés' },
    ]},
    { title: 'AU PARKING - ARRÊT MOTEUR', items: [
        { item: 'Régime 1200 trs/min' },
        { item: 'Freins serrés (pieds sur les freins)' },
        { item: 'Top chrono noté' },
        { item: 'Contact radio PARKING pour quitter' },
        { item: 'Transpondeur sur 7000 puis sur OFF' },
        { item: 'Radio + RadioNav sur OFF' },
        { item: 'Alternateur sur OFF' },
        { item: 'Bille maquette sur OFF' },
        { item: 'Essais coupure 900 trs/min' },
        { item: 'Régime 1200 trs/min' },
        { item: 'Mixture tirée plein pauvre' },
        { item: 'Contact magnétos sur OFF' },
        { item: 'Retirer clés' },
        { item: 'Phare sur OFF' },
        { item: 'Feux de nav sur OFF' },
        { item: 'Beacon = laissé sur ON' },
        { item: 'Batterie sur OFF' },
        { item: 'Horamètre noté' },
    ]},
    { title: 'APRES VOL', items: [
        { item: 'Cache pitot remis' },
        { item: 'Avion à laver' },
        { item: 'Documents à remplir' },
        { item: 'Tableau des pannes ACP (si nécessaire)' },
        { item: 'Remettre les clés' },
        { item: 'Vérifier carte essence dans carnet de route' },
        { item: 'Remettre les casques si casques du club' },
        { item: 'Carnet de route' },     
        { item: 'OpenFlyers' },
        { item: 'Planche Club' },
        { item: 'Carnet de vol' },
        { item: 'Carnet Perso (le cas échéant)' },
        { item: 'Faire signer vol (si instruction)' },
    ]},
];

const giyaChecklistContent: ChecklistSection[] = [
    { title: 'PARAMETRES', items: [
        { item: 'Rotation = 50 kt' },
        { item: 'Montée = 70 kt' },
        { item: 'Finale = 60 kt' },
        { item: 'Finesse max = 60 kt' },
    ]},
    { title: 'AVANT VOL', items: [
        { item: 'Inscription planche club' },
        { item: 'Documents Avion/Pilote à bord' },
        { item: 'Météo & Notams vérifiés' },
        { item: 'Masse et centrage effectué' },
    ]},
    { title: 'PRE-VOL EXTERIEURE', items: [
        { item: 'Purges effectuées' },
        { item: 'Essence' },
        { item: 'Feux vérifiés' },
        { item: 'Alarme décrochage testée' },
        { item: 'Cache Pitot enlevé' },
        { item: 'Barre de guidage enlevée' },
        { item: 'Niveau d\'huile vérifié' },
        { item: 'Nettoyer surfaces vitrées' },
    ]},
    { title: 'PRE-VOL INTERIEURE', items: [
        { item: 'Clés retirées / dans cockpit' },
        { item: 'Ceintures attachées' },
        { item: 'Casques branchés' },
        { item: 'Commandes : libres ET dans le bon sens' },
        { item: 'Masse et centrage vérifié' },
        { item: 'Distances décollage / atterrissages vérifiées' },
        { item: 'Breakers en place' },
        { item: 'Briefing Passager' },
    ]},
    { title: 'MISE EN ROUTE', items: [
        { item: 'Portes fermées (bien vérifier)' },
        { item: 'Freins serrés (pieds sur les freins)' },
        { item: 'Essence sur ouvert' },
        { item: 'Mixture plein riche - poussée' },
        { item: 'Horamètre noté' },
        { item: 'Radio + RadioNav sur OFF' },
        { item: 'Batterie sur ON' },
        { item: 'Volets rentrés' },
        { item: 'Moteur froid → réchauffe carbu' },
        { item: 'Clés en place, sur BOTH' },
        { item: 'Injections 1 à 4 selon température (8 en hiver)' },
        { item: 'Gaz 1cm maxi' },
        { item: 'Beacon sur ON' },
        { item: 'Feux NAV si vol de nuit' },
        { item: 'Sécurité → abords dégagés' },
        { item: 'Démarreur (max 10 secondes)' },
        { item: 'Régime 1200 trs/min' },
        { item: 'Pression huile vérifiée (plage verte)' },
    ]},
    { title: 'APRES MISE EN ROUTE', items: [
        { item: 'Top chrono noté' },
        { item: 'Réchauffe carbu repoussée (froid)' },
        { item: 'Régime 1200 trs/min' },
        { item: 'Alternateur sur ON' },
        { item: 'Gyros, dépression OK' },
        { item: 'Radio + RadioNav sur ON' },
        { item: 'Fréquences et volumes vérifiés' },
        { item: 'Transpondeur sur ALT + 7000' },
        { item: 'Altimètre réglé au QNH' },
        { item: 'Conservateur de Cap réglé' },
        { item: 'Compensateur vérifié (position décollage)' },
        { item: 'ATIS noté' },
        { item: 'Briefing roulage effectué' },
        { item: 'Phare sur ON' },
        { item: 'Contact radio BONJOUR' },
        { item: 'Top chrono' },
    ]},
    { title: 'ROULAGE', items: [
        { item: 'Freins : essayés' },
        { item: 'Horizon artificiel stable' },
        { item: 'Conservateur de cap + Compas vérifiés' },
        { item: 'Bille maquette dans le bon sens' },
    ]},
    { title: 'AU POINT D\'ATTENTE', items: [
        { item: 'Freins serrés (pieds sur les freins)' },
        { item: 'Régime 1200 trs/min' },
        { item: 'Phare sur OFF' },
        { item: 'T° huile suffisante' },
        { item: 'Réchauffe carbu poussée (froid)' },
        { item: 'Régime 1800 tr/min' },
        { item: 'Tests magnétos (perte 150 max | 75 entre les 2)' },
        { item: 'Réchauffe carbu testée (<200 trs/min)' },
        { item: 'Ralenti (moteur ne cale pas)' },
        { item: 'Régime 1200 trs/min' },
    ]},
    { title: 'AVANT ALIGNEMENT', items: [
        { item: 'Batterie sur ON' },
        { item: 'Alternateur sur ON' },
        { item: 'Contact magnéto sur BOTH' },
        { item: 'Réchauffe Carbu poussée (froid)' },
        { item: 'Mixture plein riche (poussée)' },
        { item: 'Essence = robinet ouvert' },
        { item: 'Huile = Pression / T° plages vertes' },
        { item: 'Volets essayés + position décollage' },
        { item: 'Horizon artificiel réglé' },
        { item: 'Bille maquette OK' },
        { item: 'Conservateur de cap réglé' },
        { item: 'Variomètre OK' },
        { item: 'Portes fermées (bien vérifier)' },
        { item: 'Ceintures attachés' },
        { item: 'Altimètre au QNH' },
        { item: 'Commandes libre ET dans le bon sens' },
        { item: 'Briefing PANNES AU DECOLLAGE' },
        { item: 'Briefing départ' },
        { item: 'Phare sur ON' },
        { item: 'Contact radio PRET au POINT d\'ATTENTE' },
    ]},
    { title: 'ALIGNEMENT / DECOLLAGE', items: [
        { item: 'Conservateur de cap réglé' },
        { item: 'Pleine puissance (mini 2150 trs/min)' },
        { item: 'TOP CHRONO Noté' },
        { item: 'Rotation = 50 kt' },
        { item: 'Montée = 70 kt' },
        { item: '300 ft/sol = volets rentrés' },
        { item: '500 ft/sol = phare OFF' },
    ]},
    { title: 'APRES ATTERRISSAGE', items: [
        { item: 'Piste dégagée' },
        { item: 'Régime 1200 trs/min' },
        { item: 'Réchauffe carbu poussée (froid)' },
        { item: 'Compensateur au neutre' },
        { item: 'Volets rentrés' },
    ]},
    { title: 'AU PARKING - ARRÊT MOTEUR', items: [
        { item: 'Régime 1200 trs/min' },
        { item: 'Freins serrés (pieds sur les freins)' },
        { item: 'Top chrono noté' },
        { item: 'Contact radio PARKING pour quitter' },
        { item: 'Transpondeur sur 7000 puis sur OFF' },
        { item: 'Radio + RadioNav sur OFF' },
        { item: 'Alternateur sur OFF' },
        { item: 'Essais coupure 900 trs/min' },
        { item: 'Régime 1200 trs/min' },
        { item: 'Mixture tirée plein pauvre' },
        { item: 'Contact magnétos sur OFF' },
        { item: 'Retirer clés' },
        { item: 'Beacon = laissé sur ON' },
        { item: 'Phare sur OFF' },
        { item: 'Feux de nav sur OFF' },
        { item: 'Batterie sur OFF' },
        { item: 'Horamètre noté' },
    ]},
    { title: 'APRES VOL', items: [
        { item: 'Cache pitot remis' },
        { item: 'Avion à laver' },
        { item: 'Documents à remplir' },
        { item: 'Tableau des pannes ACP (si nécessaire)' },
        { item: 'Remettre les clés' },
        { item: 'Vérifier carte essence dans carnet de route' },
        { item: 'Remettre les casques si casques du club' },
        { item: 'Carnet de route' },     
        { item: 'OpenFlyers' },
        { item: 'Planche Club' },
        { item: 'Carnet de vol' },
        { item: 'Carnet Perso (le cas échéant)' },
        { item: 'Faire signer vol (si instruction)' },
    ]},
];

const gkqaChecklistContent: ChecklistSection[] = [
    { title: 'PARAMETRES', items: [
        { item: 'Rotation = 100 km/h' },
        { item: 'Montée = 150 km/h' },
        { item: 'Finale = 120 km/h' },
        { item: 'Finesse max = 150 km/h' },
    ]},
    { title: 'AVANT VOL', items: [
        { item: 'Inscription planche club' },
        { item: 'Documents Avion/Pilote à bord' },
        { item: 'Météo & Notams vérifiés' },
        { item: 'Masse et centrage effectué' },
    ]},
    { title: 'PRE-VOL EXTERIEURE', items: [
        { item: 'Purges effectuées' },
        { item: 'Essence' },
        { item: 'Feux vérifiés' },
        { item: 'Alarme décrochage testée' },
        { item: 'Cache Pitot enlevé' },
        { item: 'Barre de guidage enlevée' },
        { item: 'Niveau d\'huile vérifié' },
        { item: 'Nettoyer surfaces vitrées' },
    ]},
    { title: 'PRE-VOL INTERIEURE', items: [
        { item: 'Clés retirées / dans cockpit' },
        { item: 'Ceintures attachées' },
        { item: 'Casques branchés' },
        { item: 'Commandes : libres ET dans le bon sens' },
        { item: 'Masse et centrage vérifié' },
        { item: 'Distances décollage / atterrissages vérifiées' },
        { item: 'Breakers en place' },
        { item: 'Briefing Passager' },
    ]},
    { title: 'MISE EN ROUTE', items: [
        { item: 'Verrière fermée' },
        { item: 'Frein de parc serré' },
        { item: 'Essence sur ouvert' },
        { item: 'Mixture plein riche - poussée' },
        { item: 'MASTER RADIO sur OFF' },
        { item: 'Horamètre noté' },
        { item: 'Batterie sur ON' },
        { item: 'Volets rentrés' },
        { item: 'Moteur froid → réchauffe carbu' },
        { item: 'Clés en place, sur BOTH' },
        { item: 'Pompe électrique sur ON' },
        { item: 'Pressions vérifiés' },
        { item: 'Injections 1 à 4 selon température (8 en hiver)' },
        { item: 'Gaz 1cm maxi' },
        { item: 'Beacon sur ON' },
        { item: 'Feux NAV si vol de nuit' },
        { item: 'Sécurité → abords dégagés' },
        { item: 'Démarreur (max 10 secondes)' },
        { item: 'Régime 1200 trs/min' },
        { item: 'Pression huile vérifiée (plage verte)' },
    ]},
    { title: 'APRES MISE EN ROUTE', items: [
        { item: 'Top chrono noté' },
        { item: 'Réchauffe carbu repoussée (froid)' },
        { item: 'Régime 1200 trs/min' },
        { item: 'Alternateur sur ON' },
        { item: 'Pompe électrique sur OFF' },
        { item: 'MASTER RADIO sur ON' },
        { item: 'Gyros, dépression OK' },
        { item: 'Radio + RadioNav sur ON' },
        { item: 'Fréquences et volumes vérifiés' },
        { item: 'Transpondeur sur ALT + 7000' },
        { item: 'Altimètre réglé au QNH' },
        { item: 'Conservateur de Cap réglé' },
        { item: 'Compensateur vérifié (position décollage)' },
        { item: 'ATIS noté' },
        { item: 'Briefing roulage effectué' },
        { item: 'Phare sur ON' },
        { item: 'Contact radio BONJOUR' },
        { item: 'Top chrono' },
    ]},
    { title: 'ROULAGE', items: [
        { item: 'Freins : essayés' },
        { item: 'Horizon artificiel stable' },
        { item: 'Conservateur de cap + Compas vérifiés' },
        { item: 'Bille maquette dans le bon sens' },
    ]},
    { title: 'AU POINT D\'ATTENTE', items: [
        { item: 'Frein de parc serré' },
        { item: 'Régime 1200 trs/min' },
        { item: 'Phare sur OFF' },
        { item: 'T° huile suffisante' },
        { item: 'Réchauffe carbu poussée' },
        { item: 'Régime 1800 tr/min' },
        { item: 'Tests magnétos (perte 150 max | 75 entre les 2)' },
        { item: 'Réchauffe carbu testée ( < 200 trs/min)' },
        { item: 'Ralenti (moteur ne cale pas)' },
        { item: 'Régime 1200 trs/min' },
    ]},
    { title: 'AVANT ALIGNEMENT', items: [
        { item: 'Batterie sur ON' },
        { item: 'Alternateur sur ON' },
        { item: 'Contact magnéto sur BOTH' },
        { item: 'Voyants testés' },
        { item: 'Réchauffe Carbu poussée (froid)' },
        { item: 'Mixture plein riche (poussée)' },
        { item: 'Essence = robinet ouvert' },
        { item: 'Pompe électrique sur ON' },
        { item: 'Huile = Pression / T° plages vertes' },
        { item: 'Volets essayés position décollage' },
        { item: 'Horizon artificiel réglé' },
        { item: 'Bille maquette OK' },
        { item: 'Conservateur de cap réglé' },
        { item: 'Variomètre OK' },
        { item: 'Verrière fermée' },
        { item: 'Ceintures attachés' },
        { item: 'Altimètre au QNH' },
        { item: 'Phare sur ON' },
        { item: 'Commandes libre ET dans le bon sens' },
        { item: 'Briefing PANNES AU DECOLLAGE' },
        { item: 'Briefing départ' },
        { item: 'Contact radio PRET au POINT d\'ATTENTE' },
    ]},
    { title: 'ALIGNEMENT / DECOLLAGE', items: [
        { item: 'Conservateur de cap réglé' },
        { item: 'Puissance mini 2200 tr/min' },
        { item: 'TOP CHRONO Noté' },
        { item: 'Rotation = 100 km/h' },
        { item: 'Montée = 150 km/h' },
        { item: '300 ft/sol = volets rentrés' },
        { item: '500 ft/sol = phare OFF' },
        { item: '500 ft/sol = pompe OFF' },
        { item: 'Pression vérifiée' },
    ]},
    { title: 'APRES ATTERRISSAGE', items: [
        { item: 'Piste dégagée' },
        { item: 'Régime 1200 trs/min' },
        { item: 'Réchauffe carbu poussée (froid)' },
        { item: 'Pompe élctrique OFF' },
        { item: 'Compensateur au neutre' },
        { item: 'Volets rentrés' },
    ]},
    { title: 'AU PARKING - ARRÊT MOTEUR', items: [
        { item: 'Régime 1200 trs/min' },
        { item: 'Frein de parc serré' },
        { item: 'Top chrono noté' },
        { item: 'Contact radio PARKING pour quitter' },
        { item: 'Transpondeur sur 7000 puis sur OFF' },
        { item: 'MASTER RADIO sur OFF' },
        { item: 'Alternateur sur OFF' },
        { item: 'Essais coupure 900 trs/min' },
        { item: 'Régime 1200 trs/min' },
        { item: 'Mixture tirée plein pauvre' },
        { item: 'Contact magnétos sur OFF' },
        { item: 'Retirer clés' },
        { item: 'Beacon = laisser sur ON' },
        { item: 'Batterie sur OFF' },
        { item: 'Phares sur OFF' },
        { item: 'Feux de nav sur OFF' },
        { item: 'Sortir 2 crans de volets' },
        { item: 'Horamètre noté' },
    ]},
    { title: 'APRES VOL', items: [
        { item: 'Cache pitot remis (+ sondes statiques)' },
        { item: 'Avion à laver' },
        { item: 'Documents à remplir' },
        { item: 'Tableau des pannes ACP (si nécessaire)' },
        { item: 'Remettre les clés' },
        { item: 'Vérifier carte essence dans carnet de route' },
        { item: 'Remettre les casques si casques du club' },
        { item: 'Carnet de route' },     
        { item: 'OpenFlyers' },
        { item: 'Planche Club' },
        { item: 'Carnet de vol' },
        { item: 'Carnet Perso (le cas échéant)' },
        { item: 'Faire signer vol (si instruction)' },
    ]},
];

const glvxChecklistContent: ChecklistSection[] = [
    { title: 'PARAMETRES', items: [
        { item: 'Rotation = 100 km/h' },
        { item: 'Montée = 150 km/h' },
        { item: 'Finale = 120 km/h' },
        { item: 'Finesse max = 150 km/h' },
    ]},
    { title: 'AVANT VOL', items: [
        { item: 'Inscription planche club' },
        { item: 'Documents Avion/Pilote à bord' },
        { item: 'Météo & Notams vérifiés' },
        { item: 'Masse et centrage effectué' },
    ]},
    { title: 'PRE-VOL EXTERIEURE', items: [
        { item: 'Purges effectuées' },
        { item: 'Essence' },
        { item: 'Feux vérifiés' },
        { item: 'Alarme décrochage testée' },
        { item: 'Cache Pitot enlevé' },
        { item: 'Barre de guidage enlevée' },
        { item: 'Niveau d\'huile vérifié' },
        { item: 'Nettoyer surfaces vitrées' },
    ]},
    { title: 'PRE-VOL INTERIEURE', items: [
        { item: 'Clés retirées / dans cockpit' },
        { item: 'Ceintures attachées' },
        { item: 'Casques branchés' },
        { item: 'Commandes : libres ET dans le bon sens' },
        { item: 'Masse et centrage vérifié' },
        { item: 'Distances décollage / atterrissages vérifiées' },
        { item: 'Vanne réservoir auxiliaire : poussée - fermée' },
        { item: 'Breakers en place' },
        { item: 'Briefing Passager' },
    ]},
    { title: 'MISE EN ROUTE', items: [
        { item: 'Verrière fermée' },
        { item: 'Frein de parc serré' },
        { item: 'Essence sur ouvert' },
        { item: 'Mixture plein riche - poussée' },
        { item: 'MASTER RADIO sur OFF' },
        { item: 'Horamètre noté' },
        { item: 'Batterie sur ON' },
        { item: 'Volets rentrés' },
        { item: 'Moteur froid → réchauffe carbu' },
        { item: 'Clés en place, sur BOTH' },
        { item: 'Pompe électrique sur ON' },
        { item: 'Pressions vérifiés' },
        { item: 'Injections 1 à 4 selon température (8 en hiver)' },
        { item: 'Gaz 1cm maxi' },
        { item: 'Beacon sur ON' },
        { item: 'Feux NAV si vol de nuit' },
        { item: 'Sécurité → abords dégagés' },
        { item: 'Démarreur (max 10 secondes)' },
        { item: 'Régime 1200 trs/min' },
        { item: 'Pression huile vérifiée (plage verte)' },
    ]},
    { title: 'APRES MISE EN ROUTE', items: [
        { item: 'Top chrono noté' },
        { item: 'Réchauffe carbu repoussée (froid)' },
        { item: 'Régime 1200 trs/min' },
        { item: 'Alternateur sur ON' },
        { item: 'Pompe électrique sur OFF' },
        { item: 'MASTER RADIO sur ON' },
        { item: 'Gyros, dépression OK' },
        { item: 'Radio + RadioNav sur ON' },
        { item: 'Fréquences et volumes vérifiés' },
        { item: 'Transpondeur sur ALT + 7000' },
        { item: 'Altimètre réglé au QNH' },
        { item: 'Conservateur de Cap réglé' },
        { item: 'Compensateur vérifié (position décollage)' },
        { item: 'ATIS noté' },
        { item: 'Briefing roulage effectué' },
        { item: 'Phare sur ON' },
        { item: 'Contact radio BONJOUR' },
        { item: 'Top chrono' },
    ]},
    { title: 'ROULAGE', items: [
        { item: 'Freins : essayés' },
        { item: 'Horizon artificiel stable' },
        { item: 'Conservateur de cap + Compas vérifiés' },
        { item: 'Bille maquette dans le bon sens' },
    ]},
    { title: 'AU POINT D\'ATTENTE', items: [
        { item: 'Frein de parc serré' },
        { item: 'Régime 1200 trs/min' },
        { item: 'Phare sur OFF' },
        { item: 'T° huile suffisante' },
        { item: 'Réchauffe carbu poussée' },
        { item: 'Régime 1800 tr/min' },
        { item: 'Tests magnétos (perte 150 max | 75 entre les 2)' },
        { item: 'Réchauffe carbu testée ( < 200 trs/min)' },
        { item: 'Ralenti (moteur ne cale pas)' },
        { item: 'Régime 1200 trs/min' },
    ]},
    { title: 'AVANT ALIGNEMENT', items: [
        { item: 'Batterie sur ON' },
        { item: 'Alternateur sur ON' },
        { item: 'Contact magnéto sur BOTH' },
        { item: 'Voyants testés' },
        { item: 'Réchauffe Carbu poussée (froid)' },
        { item: 'Mixture plein riche (poussée)' },
        { item: 'Essence = robinet ouvert' },
        { item: 'Pompe électrique sur ON' },
        { item: 'Huile = Pression / T° plages vertes' },
        { item: 'Volets essayés position décollage' },
        { item: 'Horizon artificiel réglé' },
        { item: 'Bille maquette OK' },
        { item: 'Conservateur de cap réglé' },
        { item: 'Variomètre OK' },
        { item: 'Verrière fermée' },
        { item: 'Ceintures attachés' },
        { item: 'Altimètre au QNH' },
        { item: 'Phare sur ON' },
        { item: 'Commandes libre ET dans le bon sens' },
        { item: 'Briefing PANNES AU DECOLLAGE' },
        { item: 'Briefing départ' },
        { item: 'Contact radio PRET au POINT d\'ATTENTE' },
    ]},
    { title: 'ALIGNEMENT / DECOLLAGE', items: [
        { item: 'Conservateur de cap réglé' },
        { item: 'Puissance mini 2200 tr/min' },
        { item: 'TOP CHRONO Noté' },
        { item: 'Rotation = 100 km/h' },
        { item: 'Montée = 150 km/h' },
        { item: '300 ft/sol = volets rentrés' },
        { item: '500 ft/sol = phare OFF' },
        { item: '500 ft/sol = pompe OFF' },
        { item: 'Pression vérifiée' },
    ]},
    { title: 'APRES ATTERRISSAGE', items: [
        { item: 'Piste dégagée' },
        { item: 'Régime 1200 trs/min' },
        { item: 'Réchauffe carbu poussée (froid)' },
        { item: 'Pompe élctrique OFF' },
        { item: 'Compensateur au neutre' },
        { item: 'Volets rentrés' },
    ]},
    { title: 'AU PARKING - ARRÊT MOTEUR', items: [
        { item: 'Régime 1200 trs/min' },
        { item: 'Frein de parc serré' },
        { item: 'Top chrono noté' },
        { item: 'Contact radio PARKING pour quitter' },
        { item: 'Transpondeur sur 7000 puis sur OFF' },
        { item: 'MASTER RADIO sur OFF' },
        { item: 'Alternateur sur OFF' },
        { item: 'Essais coupure 900 trs/min' },
        { item: 'Régime 1200 trs/min' },
        { item: 'Mixture tirée plein pauvre' },
        { item: 'Contact magnétos sur OFF' },
        { item: 'Retirer clés' },
        { item: 'Beacon = laisser sur ON' },
        { item: 'Phares sur OFF' },
        { item: 'Feux de nav sur OFF' },
        { item: 'Batterie sur OFF' },
        { item: 'Sortir 2 crans de volets' },
        { item: 'Horamètre noté' },
    ]},
    { title: 'APRES VOL', items: [
        { item: 'Cache pitot remis (+ sondes statiques)' },
        { item: 'Avion à laver' },
        { item: 'Documents à remplir' },
        { item: 'Tableau des pannes ACP (si nécessaire)' },
        { item: 'Remettre les clés' },
        { item: 'Vérifier carte essence dans carnet de route' },
        { item: 'Remettre les casques si casques du club' },
        { item: 'Carnet de route' },     
        { item: 'OpenFlyers' },
        { item: 'Planche Club' },
        { item: 'Carnet de vol' },
        { item: 'Carnet Perso (le cas échéant)' },
        { item: 'Faire signer vol (si instruction)' },
    ]},
];

const hmpiChecklistContent: ChecklistSection[] = [
    { title: 'PARAMETRES', items: [
        { item: 'Rotation = 50 kt' },
        { item: 'Montée = 60 kt' },
        { item: 'Finale = 60 kt' },
        { item: 'Finesse max = 60 kt' },
    ]},
    { title: 'AVANT VOL', items: [
        { item: 'Inscription planche club' },
        { item: 'Documents Avion/Pilote à bord' },
        { item: 'Météo & Notams vérifiés' },
        { item: 'Masse et centrage effectué' },
    ]},
    { title: 'PRE-VOL EXTERIEURE', items: [
        { item: 'Purges effectuées' },
        { item: 'Essence' },
        { item: 'Feux vérifiés' },
        { item: 'Alarme décrochage testée' },
        { item: 'Cache Pitot enlevé' },
        { item: 'Protections d\'hélice enlevées' },
        { item: 'Protections d\'ailes enlevées' },
        { item: 'Barre de guidage enlevée' },
        { item: 'Niveau d\'huile vérifié' },
        { item: 'Nettoyer surfaces vitrées' },
    ]},
    { title: 'PRE-VOL INTERIEURE', items: [
        { item: 'Clés retirées / dans cockpit' },
        { item: 'Palonniers réglés (mettre coussin si besoin)' },
        { item: 'Ceintures attachées' },
        { item: 'Casques branchés' },
        { item: 'Commandes : libres ET dans le bon sens' },
        { item: 'Masse et centrage vérifié' },
        { item: 'Distances décollage / atterrissages vérifiées' },
        { item: 'Breakers en place' },
        { item: 'Briefing Passager' },
    ]},
    { title: 'MISE EN ROUTE', items: [
        { item: 'Verrière fermée (2 clics)' },
        { item: 'Freins serrés (pieds sur les freins)' },
        { item: 'Avionics switch sur OFF' },
        { item: 'IC (InterCom) sur OFF' },
        { item: 'Master Switch sur OFF' },
        { item: 'Horamètre noté' },
        { item: 'Volets rentrés' },
        { item: 'Essence : ouvert sur le réservoir le MOINS plein' },
        { item: 'Réchauffe carbu si T°ext<15°C : tirée - chaud' },     
        { item: 'Clés en place, sur BOTH' },
        { item: 'Gaz TOUT REDUIT' },
        { item: 'Fuel Pump sur ON' },
        { item: 'CHOKE (starter) : moteur froid tiré comme nécessaire selon T°' },
        { item: 'Beacon sur ON' },
        { item: 'Sécurité → abords dégagés' },
        { item: 'Démarreur (max 10 secondes)' },
        { item: 'CHOKE (starter) repoussé lentement'},
        { item: 'Régime 2000 trs/min MAX | NE PAS DEPASSER !', isWarning:true },
        { item: 'Pression huile vérifiée (plage verte dans les 10 sec → >0.8 bar)' },
    ]},
    { title: 'APRES MISE EN ROUTE', items: [
        { item: 'Top chrono noté' },
        { item: 'PENDANT 2min NE PAS DEPASSER les 2000 trs/min !', isWarning:true },
        { item: 'Fuel Pump sur OFF (pression vérifiée)' },
        { item: 'Réchauffe carbu repoussée (froid)' },
        { item: 'Avionics Switch sur ON' },
        { item: 'IC (InterCom) sur ON' },
        { item: 'Instr. (dir. Gyro - Horizon - Turn ind.) sur ON' },
        { item: 'Transpondeur sur ALT + 7000' },
        { item: 'Altimètre réglé au QNH' },
        { item: 'Horizon artificiel : cagé et maquette réglé' },
        { item: 'Conservateur de Cap réglé' },
        { item: 'Régime après 2 min : 2300 à 2500 trs/min' },
        { item: 'Voyant Charging éteint' },
        { item: 'ATIS noté' },
        { item: 'T° huile >40°C' },
        { item: 'Compensateur vérifié (position décollage)' },
        { item: 'Fréquences et volumes vérifiés' },
        { item: 'SQUELCH sur auto' },
        { item: 'Briefing roulage effectué' },
        { item: 'Phare sur ON' },
        { item: 'Contact radio BONJOUR' },
        { item: 'Top chrono' },
    ]},
    { title: 'ROULAGE', items: [
        { item: 'Freins : essayés' },
        { item: 'Horizon artificiel stable' },
        { item: 'Conservateur de cap + Compas vérifiés' },
        { item: 'Bille maquette dans le bon sens' },
        { item: 'Aux GEN clignote' },
    ]},
    { title: 'AU POINT D\'ATTENTE', items: [
        { item: 'Freins serrés (pieds sur les freins)' },
        { item: 'Phare sur OFF' },
        { item: 'Régime entre 2300 et 2500 trs/min' },
        { item: 'Réservoir sur le PLUS plein' },
        { item: 'Instruments moteur : arc vert (sauf T° huile 50°C mini)' },
        { item: 'Panneau d\'alarme : vérifié éteint' },
        { item: 'Réchauffe carbu poussée (froid)' },
        { item: 'Régime 4000 tr/min' },
        { item: 'Tests magnétos (perte 300 max | 120 entre les 2)' },
        { item: 'Réchauffe carbu testée (<100 trs/min)' },
        { item: 'Ralenti (moteur ne cale pas | mini 1400 trs/min)' },
        { item: 'Régime 2300 à 2500 trs/min' },
    ]},
    { title: 'AVANT ALIGNEMENT', items: [
        { item: 'Master Switch sur ON' },
        { item: 'Contact magnéto sur BOTH' },
        { item: 'Réchauffe Carbu poussée (froid)' },
        { item: 'CHOKE (starter) : repoussé | DECOLLAGE INTERDIT SI STARTER ENCLENCHE !', isWarning:true},
        { item: 'Huile = Pression / T° mini 50°C + pression dans le vert' },
        { item: 'Volets essayés + position décollage 1 cran 15° (+ message)' },
        { item: 'Verrière verrouillée (pas de message d\'alerte)' },
        { item: 'Harnais attachés' },
        { item: 'Horizon artificiel réglé' },
        { item: 'Bille maquette OK' },
        { item: 'Conservateur de cap réglé' },
        { item: 'Variomètre OK' },
        { item: 'Altimètre au QNH' },
        { item: 'Commandes libre ET dans le bon sens' },
        { item: 'Briefing PANNES AU DECOLLAGE' },
        { item: 'Briefing départ' },
        { item: 'Phare sur ON' },
        { item: 'Contact radio PRET au POINT d\'ATTENTE' },
    ]},
    { title: 'ALIGNEMENT / DECOLLAGE', items: [
        { item: 'Conservateur de cap réglé' },
        { item: 'Pleine puissance (mini 5000 trs/min)' },
        { item: 'TOP CHRONO Noté' },
        { item: 'Rotation = 50 kt' },
        { item: 'Montée = 60 kt' },
        { item: '300 ft/sol = volets rentrés' },
        { item: '500 ft/sol = phare OFF' },
        { item: '500 ft/sol = pompe OFF + pression vérifiée' },
    ]},
    { title: 'APRES ATTERRISSAGE', items: [
        { item: 'Piste dégagée' },
        { item: 'Régime 2300 à 2500 trs/min' },
        { item: 'Réchauffe carbu poussée (froid)' },
        { item: 'Compensateur au neutre' },
        { item: 'Volets rentrés' },
        { item: 'Fuel Pump OFF' },
    ]},
    { title: 'AU PARKING - ARRÊT MOTEUR', items: [
        { item: 'Régime 2300 à 2500 trs/min' },
        { item: 'Freins serrés (pieds sur les freins)' },
        { item: 'Top chrono noté' },
        { item: 'Contact radio PARKING pour quitter' },
        { item: 'Transpondeur sur 7000 puis sur OFF' },
        { item: 'Avionics Switch sur OFF' },
        { item: 'IC (InterCom) sur OFF' },
        { item: 'Dir. Gyro - Horieon - Turn Ind sur OFF' },
        { item: 'Régime sur ralenti' },
        { item: 'Contact magnétos : gauche maintenir 2 sec' },
        { item: 'Contact magnétos : droite maintenir 2 sec' },
        { item: 'Contact magnétos : OFF' },
        { item: 'Retirer clés' },
        { item: 'Phare sur OFF' },
        { item: 'Feux de nav sur OFF' },
        { item: 'Beacon = laissé sur ON' },
        { item: 'Horamètre noté' },
        { item: 'Master Switch sur OFF' },
    ]},
    { title: 'APRES VOL', items: [
        { item: 'Cache pitot remis' },
        { item: 'Avion à laver' },
        { item: 'Protections ailes + hélices' },
        { item: 'Documents à remplir' },
        { item: 'Tableau des pannes ACP (si nécessaire)' },
        { item: 'Remettre les clés' },
        { item: 'Vérifier carte essence dans carnet de route' },
        { item: 'Remettre les casques si casques du club' },
        { item: 'Carnet de route' },     
        { item: 'OpenFlyers' },
        { item: 'Planche Club' },
        { item: 'Carnet de vol' },
        { item: 'Carnet Perso (le cas échéant)' },
        { item: 'Faire signer vol (si instruction)' },
    ]},
];

const hnnyChecklistContent: ChecklistSection[] = [
    { title: 'PARAMETRES', items: [
        { item: 'Rotation = 50 kt' },
        { item: 'Montée = 60 kt' },
        { item: 'Finale = 60 kt' },
        { item: 'Finesse max = 60 kt' },
    ]},
    { title: 'AVANT VOL', items: [
        { item: 'Inscription planche club' },
        { item: 'Documents Avion/Pilote à bord' },
        { item: 'Météo & Notams vérifiés' },
        { item: 'Masse et centrage effectué' },
    ]},
    { title: 'PRE-VOL EXTERIEURE', items: [
        { item: 'Purges effectuées' },
        { item: 'Essence' },
        { item: 'Feux vérifiés' },
        { item: 'Alarme décrochage testée' },
        { item: 'Cache Pitot enlevé' },
        { item: 'Protections d\'hélice enlevées' },
        { item: 'Protections d\'ailes enlevées' },
        { item: 'Barre de guidage enlevée' },
        { item: 'Niveau d\'huile vérifié' },
        { item: 'Nettoyer surfaces vitrées' },
    ]},
    { title: 'PRE-VOL INTERIEURE', items: [
        { item: 'Clés retirées / dans cockpit' },
        { item: 'Palonniers réglés (mettre coussin si besoin)' },
        { item: 'Ceintures attachées' },
        { item: 'Casques branchés' },
        { item: 'Commandes : libres ET dans le bon sens' },
        { item: 'Masse et centrage vérifié' },
        { item: 'Distances décollage / atterrissages vérifiées' },
        { item: 'Breakers en place' },
        { item: 'Briefing Passager' },
    ]},
    { title: 'MISE EN ROUTE', items: [
        { item: 'Freins serrés (pieds sur les freins)' },
        { item: 'Verrière fermée (2 clics)' },
        { item: 'Batterie G3X sur ON → attendre affichage GARMIN' },
        { item: 'Master Switch sur ON' },
        { item: 'Horamètre noté' },
        { item: 'Avionics switch sur OFF' },
        { item: 'IC (InterCom) sur OFF' },
        { item: 'Crew Alerting System (EMS) : sans alerte (témoin EMS ne clignote pas)' },
        { item: 'Volets rentrés' },
        { item: 'Essence : ouvert sur le réservoir le MOINS plein' },
        { item: 'Réchauffe carbu si T°ext<15°C : tirée - chaud' },     
        { item: 'Clés en place, sur BOTH' },
        { item: 'Gaz TOUT REDUIT' },
        { item: 'Fuel Pump sur ON' },
        { item: 'CHOKE (starter) : moteur froid tiré comme nécessaire selon T°' },
        { item: 'Beacon sur ON' },
        { item: 'Sécurité → abords dégagés' },
        { item: 'Démarreur (max 10 secondes)' },
        { item: 'CHOKE (starter) repoussé lentement'},
        { item: 'Régime 2000 trs/min MAX | NE PAS DEPASSER !', isWarning:true },
        { item: 'Pression huile vérifiée (plage verte dans les 10 sec → >0.8 bar)' },
    ]},
    { title: 'APRES MISE EN ROUTE', items: [
        { item: 'Top chrono noté' },
        { item: 'PENDANT 2min NE PAS DEPASSER les 2000 trs/min !' , isWarning:true},
        { item: 'GEN + Aux GEN : ON - Charge vérifiée' },
        { item: 'Fuel Pump sur OFF (pression vérifiée)' },
        { item: 'Réchauffe carbu repoussée (froid)' },
        { item: 'Avionics Switch sur ON' },
        { item: 'IC (InterCom) sur ON' },
        { item: 'Transpondeur sur ALT + 7000' },
        { item: 'Affichage EFIS : EFIS (tapes) ou SIX PACK (round gauges)' },
        { item: 'Altimètre EFIS : réglé au QNH (set for field)' },
        { item: 'Altimètre de secours : réglé au QNH' },
        { item: 'Régime après 2 min : 2300 à 2500 trs/min' },
        { item: 'Voyant Charging éteint' },
        { item: 'ATIS noté' },
        { item: 'T° huile >40°C' },
        { item: 'Compensateur vérifié (position décollage)' },
        { item: 'Fréquences et volumes vérifiés' },
        { item: 'SQUELCH sur auto' },
        { item: 'Briefing roulage effectué' },
        { item: 'Phare sur ON' },
        { item: 'Contact radio BONJOUR' },
        { item: 'Top chrono' },
    ]},
    { title: 'ROULAGE', items: [
        { item: 'Freins : essayés' },
        { item: 'Horizon artificiel stable' },
        { item: 'Conservateur de cap + Compas vérifiés' },
        { item: 'Bille maquette dans le bon sens' },
        { item: 'Aux GEN clignote' },
    ]},
    { title: 'AU POINT D\'ATTENTE', items: [
        { item: 'Freins serrés (pieds sur les freins)' },
        { item: 'Phare sur OFF' },
        { item: 'Régime entre 2300 et 2500 trs/min' },
        { item: 'Réservoir sur le PLUS plein' },
        { item: 'Instruments moteur : arc vert (sauf T° huile 50°C mini)' },
        { item: 'Panneau d\'alarme : vérifié éteint' },
        { item: 'Réchauffe carbu poussée (froid)' },
        { item: 'Régime 4000 tr/min' },
        { item: 'Tests magnétos (perte 300 max | 120 entre les 2)' },
        { item: 'Réchauffe carbu testée (<100 trs/min)' },
        { item: 'Ralenti (moteur ne cale pas | mini 1400 trs/min)' },
        { item: 'Régime 2300 à 2500 trs/min' },
    ]},
    { title: 'AVANT ALIGNEMENT', items: [
        { item: 'Master Switch sur ON' },
        { item: 'GEN + Aux GEN sur ON' },
        { item: 'Contact magnéto sur BOTH' },
        { item: 'Réchauffe Carbu poussée (froid)' },
        { item: 'CHOKE (starter) : repoussé | DECOLLAGE INTERDIT SI STARTER ENCLENCHE !', isWarning:true},
        { item: 'Huile = Pression / T° mini 50°C + pression dans le vert' },
        { item: 'Fuel pump sur ON'},
        { item: 'Volets essayés + position décollage 1 cran 15° (+ message)' },
        { item: 'Verrière verrouillée (pas de message d\'alerte)' },
        { item: 'Harnais attachés' },
        { item: 'Altimètre au QNH' },
        { item: 'Commandes libre ET dans le bon sens' },
        { item: 'Briefing PANNES AU DECOLLAGE' },
        { item: 'Briefing départ' },
        { item: 'Phare sur ON' },
        { item: 'Contact radio PRET au POINT d\'ATTENTE' },
    ]},
    { title: 'ALIGNEMENT / DECOLLAGE', items: [
        { item: 'Conservateur de cap réglé' },
        { item: 'Pleine puissance (mini 5000 trs/min)' },
        { item: 'TOP CHRONO Noté' },
        { item: 'Rotation = 50 kt' },
        { item: 'Montée = 60 kt' },
        { item: '300 ft/sol = volets rentrés' },
        { item: '500 ft/sol = phare OFF' },
        { item: '500 ft/sol = pompe OFF + pression vérifiée' },
    ]},
    { title: 'APRES ATTERRISSAGE', items: [
        { item: 'Piste dégagée' },
        { item: 'Régime 2300 à 2500 trs/min' },
        { item: 'Réchauffe carbu poussée (froid)' },
        { item: 'Compensateur au neutre' },
        { item: 'Volets rentrés' },
        { item: 'Fuel Pump OFF' },
    ]},
    { title: 'AU PARKING - ARRÊT MOTEUR', items: [
        { item: 'Régime 2300 à 2500 trs/min' },
        { item: 'Freins serrés (pieds sur les freins)' },
        { item: 'Top chrono noté' },
        { item: 'Contact radio PARKING pour quitter' },
        { item: 'Transpondeur sur 7000 puis sur OFF' },
        { item: 'Avionics Switch sur OFF' },
        { item: 'IC (InterCom) sur OFF' },
        { item: 'GEN + Aux GEN sur OFF' },
        { item: 'Régime sur ralenti' },
        { item: 'Contact magnétos : gauche maintenir 2 sec' },
        { item: 'Contact magnétos : droite maintenir 2 sec' },
        { item: 'Contact magnétos : OFF' },
        { item: 'Retirer clés' },
        { item: 'Phare sur OFF' },
        { item: 'Feux de nav sur OFF' },
        { item: 'Beacon = laissé sur ON' },
        { item: 'Horamètre noté' },
        { item: 'Master Switch sur OFF' },
        { item: 'Batterie G3X sur OFF' },
    ]},
    { title: 'APRES VOL', items: [
        { item: 'Cache pitot remis' },
        { item: 'Avion à laver' },
        { item: 'Protections ailes + hélices' },
        { item: 'Documents à remplir' },
        { item: 'Tableau des pannes ACP (si nécessaire)' },
        { item: 'Remettre les clés' },
        { item: 'Vérifier carte essence dans carnet de route' },
        { item: 'Remettre les casques si casques du club' },
        { item: 'Carnet de route' },     
        { item: 'OpenFlyers' },
        { item: 'Planche Club' },
        { item: 'Carnet de vol' },
        { item: 'Carnet Perso (le cas échéant)' },
        { item: 'Faire signer vol (si instruction)' },
    ]},
];

const hpplChecklistContent: ChecklistSection[] = [
    { title: 'PARAMETRES', items: [
        { item: 'Rotation = 50 kt' },
        { item: 'Montée = 60 kt' },
        { item: 'Finale = 60 kt' },
        { item: 'Finesse max = 60 kt' },
    ]},
    { title: 'AVANT VOL', items: [
        { item: 'Inscription planche club' },
        { item: 'Documents Avion/Pilote à bord' },
        { item: 'Météo & Notams vérifiés' },
        { item: 'Masse et centrage effectué' },
    ]},
    { title: 'PRE-VOL EXTERIEURE', items: [
        { item: 'Purges effectuées' },
        { item: 'Essence' },
        { item: 'Feux vérifiés' },
        { item: 'Alarme décrochage testée' },
        { item: 'Cache Pitot enlevé' },
        { item: 'Protections d\'hélice enlevées' },
        { item: 'Protections d\'ailes enlevées' },
        { item: 'Barre de guidage enlevée' },
        { item: 'Niveau d\'huile vérifié' },
        { item: 'Nettoyer surfaces vitrées' },
    ]},
    { title: 'PRE-VOL INTERIEURE', items: [
        { item: 'Clés retirées / dans cockpit' },
        { item: 'Palonniers réglés (mettre coussin si besoin)' },
        { item: 'Ceintures attachées' },
        { item: 'Casques branchés' },
        { item: 'Commandes : libres ET dans le bon sens' },
        { item: 'Masse et centrage vérifié' },
        { item: 'Distances décollage / atterrissages vérifiées' },
        { item: 'Breakers en place' },
        { item: 'Briefing Passager' },
    ]},
    { title: 'MISE EN ROUTE', items: [
        { item: 'Freins serrés (pieds sur les freins)' },
        { item: 'Verrière fermée (2 clics)' },
        { item: 'Master Switch sur ON' },
        { item: 'Horamètre noté' },
        { item: 'Avionics switch sur OFF' },
        { item: 'IC (InterCom) sur OFF' },
        { item: 'Volets rentrés' },
        { item: 'Essence : ouvert sur le réservoir le MOINS plein' },
        { item: 'Réchauffe carbu si T°ext<15°C : tirée - chaud' },     
        { item: 'Clés en place, sur BOTH' },
        { item: 'Gaz TOUT REDUIT' },
        { item: 'Fuel Pump sur ON' },
        { item: 'CHOKE (starter) : moteur froid tiré comme nécessaire selon T°' },
        { item: 'Beacon sur ON' },
        { item: 'Sécurité → abords dégagés' },
        { item: 'Démarreur (max 10 secondes)' },
        { item: 'CHOKE (starter) repoussé lentement'},
        { item: 'Régime 2000 trs/min MAX | NE PAS DEPASSER !', isWarning:true },
        { item: 'Pression huile vérifiée (plage verte dans les 10 sec → >0.8 bar)' },
    ]},
    { title: 'APRES MISE EN ROUTE', items: [
        { item: 'Top chrono noté' },
        { item: 'PENDANT 2min NE PAS DEPASSER les 2000 trs/min !', isWarning:true },
        { item: 'GEN + Aux GEN : ON - Charge vérifiée' },
        { item: 'Fuel Pump sur OFF (pression vérifiée)' },
        { item: 'Réchauffe carbu repoussée (froid)' },
        { item: 'Avionics Switch sur ON' },
        { item: 'IC (InterCom) sur ON' },
        { item: 'Transpondeur sur ALT + 7000' },
        { item: 'Affichage EFIS : EFIS (tapes) ou SIX PACK (round gauges)' },
        { item: 'Altimètre EFIS : réglé au QNH (set for field)' },
        { item: 'Altimètre de secours : réglé au QNH' },
        { item: 'Régime après 2 min : 2300 à 2500 trs/min' },
        { item: 'ATIS noté' },
        { item: 'T° huile >40°C' },
        { item: 'Compensateur vérifié (position décollage)' },
        { item: 'Fréquences et volumes vérifiés' },
        { item: 'SQUELCH sur auto' },
        { item: 'Briefing roulage effectué' },
        { item: 'Phare sur ON' },
        { item: 'Contact radio BONJOUR' },
        { item: 'Top chrono' },
    ]},
    { title: 'ROULAGE', items: [
        { item: 'Freins : essayés' },
        { item: 'Horizon artificiel stable' },
        { item: 'Conservateur de cap + Compas vérifiés' },
        { item: 'Bille maquette dans le bon sens' },
        { item: 'Aux GEN clignote' },
    ]},
    { title: 'AU POINT D\'ATTENTE', items: [
        { item: 'Freins serrés (pieds sur les freins)' },
        { item: 'Phare sur OFF' },
        { item: 'Régime entre 2300 et 2500 trs/min' },
        { item: 'Réservoir sur le PLUS plein' },
        { item: 'Instruments moteur : arc vert (sauf T° huile 50°C mini)' },
        { item: 'Panneau d\'alarme : vérifié éteint' },
        { item: 'Réchauffe carbu poussée (froid)' },
        { item: 'Régime 4000 tr/min' },
        { item: 'Tests magnétos (perte 300 max | 120 entre les 2)' },
        { item: 'Réchauffe carbu testée (<100 trs/min)' },
        { item: 'Ralenti (moteur ne cale pas | mini 1400 trs/min)' },
        { item: 'Régime 2300 à 2500 trs/min' },
    ]},
    { title: 'AVANT ALIGNEMENT', items: [
        { item: 'Master Switch sur ON' },
        { item: 'GEN + Aux GEN sur ON' },
        { item: 'Contact magnéto sur BOTH' },
        { item: 'Réchauffe Carbu poussée (froid)' },
        { item: 'CHOKE (starter) : repoussé | DECOLLAGE INTERDIT SI STARTER ENCLENCHE !', isWarning:true},
        { item: 'Huile = Pression / T° mini 50°C + pression dans le vert' },
        { item: 'Fuel pump sur ON'},
        { item: 'Volets essayés + position décollage 1 cran 15° (+ message)' },
        { item: 'Verrière verrouillée (pas de message d\'alerte)' },
        { item: 'Harnais attachés' },
        { item: 'Altimètre au QNH' },
        { item: 'Commandes libre ET dans le bon sens' },
        { item: 'Briefing PANNES AU DECOLLAGE' },
        { item: 'Briefing départ' },
        { item: 'Phare sur ON' },
        { item: 'Contact radio PRET au POINT d\'ATTENTE' },
    ]},
    { title: 'ALIGNEMENT / DECOLLAGE', items: [
        { item: 'Conservateur de cap réglé' },
        { item: 'Pleine puissance (mini 5000 trs/min)' },
        { item: 'TOP CHRONO Noté' },
        { item: 'Rotation = 50 kt' },
        { item: 'Montée = 60 kt' },
        { item: '300 ft/sol = volets rentrés' },
        { item: '500 ft/sol = phare OFF' },
        { item: '500 ft/sol = pompe OFF + pression vérifiée' },
    ]},
    { title: 'APRES ATTERRISSAGE', items: [
        { item: 'Piste dégagée' },
        { item: 'Régime 2300 à 2500 trs/min' },
        { item: 'Réchauffe carbu poussée (froid)' },
        { item: 'Compensateur au neutre' },
        { item: 'Volets rentrés' },
        { item: 'Fuel Pump OFF' },
    ]},
    { title: 'AU PARKING - ARRÊT MOTEUR', items: [
        { item: 'Régime 2300 à 2500 trs/min' },
        { item: 'Freins serrés (pieds sur les freins)' },
        { item: 'Top chrono noté' },
        { item: 'Contact radio PARKING pour quitter' },
        { item: 'Transpondeur sur 7000 puis sur OFF' },
        { item: 'Avionics Switch sur OFF' },
        { item: 'IC (InterCom) sur OFF' },
        { item: 'GEN + Aux GEN sur OFF' },
        { item: 'Régime sur ralenti' },
        { item: 'Contact magnétos : gauche maintenir 2 sec' },
        { item: 'Contact magnétos : droite maintenir 2 sec' },
        { item: 'Contact magnétos : OFF' },
        { item: 'Retirer clés' },
        { item: 'Phare sur OFF' },
        { item: 'Feux de nav sur OFF' },
        { item: 'Beacon = laissé sur ON' },
        { item: 'Horamètre noté' },
        { item: 'Master Switch sur OFF' },
    ]},
    { title: 'APRES VOL', items: [
        { item: 'Cache pitot remis' },
        { item: 'Avion à laver' },
        { item: 'Protections ailes + hélices' },
        { item: 'Documents à remplir' },
        { item: 'Tableau des pannes ACP (si nécessaire)' },
        { item: 'Remettre les clés' },
        { item: 'Vérifier carte essence dans carnet de route' },
        { item: 'Remettre les casques si casques du club' },
        { item: 'Carnet de route' },     
        { item: 'OpenFlyers' },
        { item: 'Planche Club' },
        { item: 'Carnet de vol' },
        { item: 'Carnet Perso (le cas échéant)' },
        { item: 'Faire signer vol (si instruction)' },
    ]},
];

export const BRIEFING_PAX_DATA = {
  id: 'BRIEFING PAX',
  title: 'Briefing Passager',
  items: [
    'Ceintures / Harnais',
    'Ouvertures (portes/verrières)',
    'Malade',
    'Aérations',
    'Savoir piloter (expliquer)',
    'Évacuation appareil',
    'Commandes libres',
    'Objets / Cabine',
    'Urgence (IVV)',
    'Radio / Communications',
    'Signaler / Solliciter',
  ]
};

export const CHECKLIST_DATA: Record<TabId, ChecklistData> = {
    'LIENS': {
        title: "Liens Utiles",
        content: [],
    },
    'NOTICE': {
        title: "Notice d'Utilisation",
        content: [],
    },
    'FAVORI': {
        title: "Choisir un Favori",
        content: [],
    },
    'RECAP': {
        title: "Récapitulatif Performances",
        content: [],
    },
    'BUBK': { title: "Checklist F-BUBK", content: bubkChecklistContent, pdfUrl: "https://www.aero-club-poitou.fr/acp/storage/app/media/Check%20list%20C150%20BK%20JFG-06-25.pdf" },
    'GIYA': { title: "Checklist F-GIYA", content: giyaChecklistContent, pdfUrl: "https://www.aero-club-poitou.fr/acp/storage/app/media/Check%20list%20C150%20YA%20JFG-06-25.pdf" },
    'GKQA': { title: "Checklist F-GKQA", content: gkqaChecklistContent, pdfUrl: "https://www.aero-club-poitou.fr/acp/storage/app/media/Check%20list%20DR400%20QA%20VX%20JFG-06-25.pdf" },
    'GLVX': { title: "Checklist F-GLVX", content: glvxChecklistContent, pdfUrl: "https://www.aero-club-poitou.fr/acp/storage/app/media/Check%20list%20DR400%20QA%20VX%20JFG-06-25.pdf" },
    'HMPI': { title: "Checklist F-HMPI", content: hmpiChecklistContent, pdfUrl: "https://www.aero-club-poitou.fr/acp/storage/app/media/Check%20list%20EVEKTOR%20PI%20JFG-05-06-25.pdf" },
    'HNNY': { title: "Checklist F-HNNY", content: hnnyChecklistContent, pdfUrl: "https://www.aero-club-poitou.fr/acp/storage/app/media/Check%20list%20EVEKTOR%20NY%20JFG-05-06-25.pdf" },
    'HPPL': { title: "Checklist F-HPPL", content: hpplChecklistContent, pdfUrl: "https://www.aero-club-poitou.fr/acp/storage/app/media/Check%20list%20EVEKTOR%20PL%20JFG-06-25.pdf" },
};